apiVersion: apps/v1
kind: Deployment
metadata:
  name: projeto-backend-deployment
  labels:
    app: projeto-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: projeto-backend
  template:
    metadata:
      labels:
        app: projeto-backend
    spec:
      containers:
      - name: container-backend
        image: projeto-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: projeto-config
        - secretRef:
            name: projeto-secret